import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SectionWrapper from "@/components/SectionWrapper";
import { Raleway, Open_Sans } from "next/font/google";

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata = {
  title: "KUTO",
  description: "Generated by the leftovers",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${raleway.className} ${openSans.className} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <SectionWrapper>
          <Header />
        </SectionWrapper>
        {children}
        <SectionWrapper>
          <Footer />
        </SectionWrapper>
      </body>
    </html>
  );
}
